#!/bin/sh
brightnessctl set +1%
sleep 0.01
brightnessctl set +1%
sleep 0.01
brightnessctl set +1%
sleep 0.01
brightnessctl set +1%
sleep 0.01
brightnessctl set +1%
sleep 0.01

dunstify -r 1 "💡 Brightness $(get-brightness)"
