#!/bin/sh

case "$(echo -e "Shutdown\nRestart\nExit\nLock" | dmenu -q -dim 0.5 -fn "Fira code:pixelsize=17" -p "Power " -i -nb "#0A0E14" -nf "#B3B1AD" -sb "#E6B450" -sf "#0A0E14")" in
        Shutdown) exec systemctl poweroff;;
        Restart) exec systemctl reboot;;
        Exit) exec i3-msg exit;;
        Lock) exec i3-lock;
esac
