#!/bin/sh

case "$(echo -e "Shutdown\nRestart\nExit\nLock" | i3-menu -p "Shutdown the system: ")" in
        Shutdown) exec systemctl poweroff;;
        Restart) exec systemctl reboot;;
        Exit) exec i3-msg exit;;
        Lock) exec i3-lock;
esac
